### ISSUE TITLE
Why are we switching to java.

### ISSUE THREAD

**Issue by Daniel-Thalman** [FRCTeam3206/Programming#1]
The main reason for wanting to switch to java is I am more comfortable with using a written language and I know I am not the only student who thinks so.  In addition to that it appeals better to people who are interested in software only stuff not just those interested in programing hardware.

**Comment by steeve-o** [comment]
Thanks Daniel. I agree with your point that Java might have more curb
appeal to students interested in getting some programming experience.

However, it's important to note that LabVIEW is also used in mainstream
engineering applications all over the place. I use LabVIEW applications
daily, and have done so at every science/engineering-type job I've ever
held. In undergrad, my department thought LabVIEW was so important that
they built a course around it. I've never had to use Java for work.
However, I'm sure others have had different experiences.

Both languages are widely used, and have their own pros and cons. Java will
present different challenges to the programmer than LabVIEW does.
Ultimately though, now is the perfect time to try Java out and see what you
think. I'm game to try to support you wherever/however possible. Should be
a good learning experience for everyone involved.

**Comment by ghost** [comment]
I support the investigation of Java with Daniel pulling the effort.  As long as the documentation is done as Raj has requested, it should be a useful process for him as well as the team.  From a philosophical standpoint, we are barely using the capabilities of LabVIEW.  Switching to Java will likely increase the difficulty of the image processing, but simplify many of the other tasks.  Either way, there is room for the team to take programming as a whole to another level.  Great potential.  As a fail-safe, we have LabVIEW that can be set up and used in a pinch.

**Comment by Daniel-Thalman** [comment]
That is part of the reason I want to start trying it out now so that if it fails or if we decide it is a lesser choice we can fall back on LabVIEW.

**Comment by ghost** [comment]
I like your enthusiasm.  Is there a programming class offered at school in Java?  Are any of the students in that class also interested in joining you?

**Comment by Daniel-Thalman** [comment]
There is an ap computer science class taught in just java i know at least myself and jessica are signed up for next year.

**Comment by steeve-o** [comment]
Daniel that's awesome. Definitely take it! Since it's AP - will it be
mostly juniors and seniors? Could be a good place to recruit some new
members.

**Comment by ghost** [comment]
I'd love to learn java so I can write real apps on my phone...  very cool that you have a high end class offering.

**Comment by RajGandhi** [comment]
This discussion seems complete.  Re-open as necessary.
