### ISSUE TITLE
Meeting April 28, 2016

### ISSUE THREAD

**Issue by RajGandhi** [FRCTeam3206/Programming#4]
Daniel, add pic and summary.

**Comment by Daniel-Thalman** [comment]
![robotics meeting pic 4 28 16](https://cloud.githubusercontent.com/assets/17950702/15001061/0595abca-115a-11e6-8da6-c8560a219852.JPG)

we decided which RFid hardware stuff we would use as well as continued to teach and learn Java.  Also broke some stuff.

**Comment by RajGandhi** [comment]
Drove Ella under Java.  Some tried Code Academy.
