### ISSUE TITLE
Meeting on May 7th

### ISSUE THREAD

**Issue by Daniel-Thalman** [FRCTeam3206/Programming#7]
Madison and steve worked on codecademy;
I Started work with rogers RFid Arduino child which is identical to the one we ordered also borrowed to work on at home (think I am almost to a solution);
next week I will pull 2 or 3 people who understand java well to learn robot applications and hopefully fix problems;
I will come up with projects for other people to work on getting better at java and programming concepts;

created problems;

**Comment by RajGandhi** [comment]
The club's RFID board arrived Monday and Jessica soldered-on headers.
